# Default values for blockscout-ens.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of blockscout-ens for `app:` labels
##
nameOverride: ""
## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""
## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []

global:
  env: testing

bens:
  image:
    repository: ghcr.io/defichain-classic/bens
    pullPolicy: Always
    tag: main
  replicaCount: 1

  ingress: 
    enabled: true
    className: ""
    annotations: {}
    hostname: chart-example.local
    paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
      enabled: false
  resources:
    limits:
      memory: 0.5Gi
      cpu: 0.25
    requests:
      memory: 0.5Gi
      cpu: 0.25

  config:
    logLevel: info
    metricsEnabled: 'false'
    tracingFormat: json
    databaseUrl: #postgres://user:password@hostname/database_name
    # OR
    databaseName: dbname
    databaseHost: postgresql
    databasePort: 5432
    databaseCredsSecretName: user.server-postgresql.credentials.postgresql.acid.zalan.do
    databaseUserSecretKey: username
    databasePasswordSecretKey: password

  env:
    # NAME: VALUE
    ##
    BENS__BLOCKSCOUT__NETWORKS__5__URL: https://eth-goerli.blockscout.com/

  podAnnotations: {}

  podSecurityContext: {}
  ## SecurityContext holds pod-level security attributes and common container settings.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext: {}
  terminationGracePeriodSeconds: 60
  ## Liveness probe
  ##
  livenessProbe:
    enabled: true
    path: /health
    params:
      initialDelaySeconds: 30
      periodSeconds: 60
      timeoutSeconds: 5
  ## Readiness probe
  ##
  readinessProbe:
    enabled: true
    path: /health
    params:
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5

  service:
    type: ClusterIP

  serviceMonitor:
    portName: metrics
    path: /metrics 
    enabled: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}
